### ISSUE TITLE
Length Mismatch Issue

### ISSUE THREAD

**Issue by sohams25** [FalchLucas/WebCamGazeEstimation#2]
I am getting the following error on running the code:

```
Total time to load model: 403.8ms
Screen Size: 1920x1080
Screen Size: 1920x1080
Webcam Size: 0x0
Traceback (most recent call last):

  File "<>/WebCamGazeEstimation/src/main.py", line 44, in <module>
    main(dir)
  File "<>/WebCamGazeEstimation/src/main.py", line 30, in main
    STransG = homtrans.calibrate(model, cap, sfm=True)
  File "<>/WebCamGazeEstimation/src/gaze_tracking/homtransform.py", line 199, in calibrate
    self.df.columns = ['Timestamp', 'idx', 'gaze_x', 'gaze_y', 'gaze_z', 'REyePos_x', 'REyePos_y', 'LEyePos_x', 'LEyePos_y', 'yaw', 'pitch', 'roll', 'HeadBox_xmin', 'HeadBox_ymin', 'RightEyeBox_xmin', 'RightEyeBox_ymin', 'LeftEyeBox_xmin', 'LeftEyeBox_ymin', 'ROpenClose','LOpenClose', 'set_x', 'set_y', 'set_z'] + 16*['WTransG']
  File "/home/<>/anaconda3/envs/2DGaze/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/<>/anaconda3/envs/2DGaze/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/<>/anaconda3/envs/2DGaze/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/<>/anaconda3/envs/2DGaze/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 39 elements
```

**Comment by FalchLucas** [comment]
The size of your webcam is 0x0, maybe your webcam is not recognized?

**Comment by daniele-agostinelli** [comment]
In main.py try 

cap=cv2.VideoCapture(0) 

instead of 

cap=cv2.VideoCapture(0, cv2.CAP_DSHOW)
